//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Host
{
    public int id { get; set; }
    public string ip { get; set; }
    public string name { get; set; }
}

public partial class HostInfo
{
    public int id { get; set; }
    public int host_id { get; set; }
    public int ipv4 { get; set; }
    public int ipv6 { get; set; }
    public int isright { get; set; }
    public System.DateTime time { get; set; }
}

public partial class LoginInfo
{
    public int id { get; set; }
    public string username { get; set; }
    public string ip { get; set; }
    public System.DateTime logintime { get; set; }
    public int status { get; set; }
}

public partial class Users
{
    public int id { get; set; }
    public string username { get; set; }
    public string password { get; set; }
    public string email { get; set; }
    public int status { get; set; }
}
